//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cypres2._0.Properties.Resources.ManoDeObra {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cypres2._0.Properties.Resources.ManoDeObra.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string BotonAceptar {
            get {
                return ResourceManager.GetString("BotonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string BotonCrear {
            get {
                return ResourceManager.GetString("BotonCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string BotonEditar {
            get {
                return ResourceManager.GetString("BotonEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BotonEliminar {
            get {
                return ResourceManager.GetString("BotonEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Listing.
        /// </summary>
        public static string BotonListadoGeneral {
            get {
                return ResourceManager.GetString("BotonListadoGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Upper.
        /// </summary>
        public static string BotonMayuscula {
            get {
                return ResourceManager.GetString("BotonMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Lower.
        /// </summary>
        public static string BotonMinuscula {
            get {
                return ResourceManager.GetString("BotonMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string BotonTerminar {
            get {
                return ResourceManager.GetString("BotonTerminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_Final.
        /// </summary>
        public static string GridC_Final {
            get {
                return ResourceManager.GetString("GridC_Final", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C_Origin.
        /// </summary>
        public static string GridC_Origen {
            get {
                return ResourceManager.GetString("GridC_Origen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string GridCodigo {
            get {
                return ResourceManager.GetString("GridCodigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GridDescripcion {
            get {
                return ResourceManager.GetString("GridDescripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string GridFecha {
            get {
                return ResourceManager.GetString("GridFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        public static string GridMoneda {
            get {
                return ResourceManager.GetString("GridMoneda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revised.
        /// </summary>
        public static string GridRevisado {
            get {
                return ResourceManager.GetString("GridRevisado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un..
        /// </summary>
        public static string GridUnidad {
            get {
                return ResourceManager.GetString("GridUnidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref. Value.
        /// </summary>
        public static string GridValorReferencia {
            get {
                return ResourceManager.GetString("GridValorReferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string MensajeEliminarFamilia {
            get {
                return ResourceManager.GetString("MensajeEliminarFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuArchivo {
            get {
                return ResourceManager.GetString("MenuArchivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string MenuFamilia {
            get {
                return ResourceManager.GetString("MenuFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string MenuImportar {
            get {
                return ResourceManager.GetString("MenuImportar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices.
        /// </summary>
        public static string MenuPrecios {
            get {
                return ResourceManager.GetString("MenuPrecios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string SubMenuCrear {
            get {
                return ResourceManager.GetString("SubMenuCrear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From a Project.
        /// </summary>
        public static string SubMenuDeProyecto {
            get {
                return ResourceManager.GetString("SubMenuDeProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string SubMenuEditar {
            get {
                return ResourceManager.GetString("SubMenuEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string SubMenuEliminar {
            get {
                return ResourceManager.GetString("SubMenuEliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete those not in use.
        /// </summary>
        public static string SubMenuEliminarManoDeObraSinUso {
            get {
                return ResourceManager.GetString("SubMenuEliminarManoDeObraSinUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group - Apply Factor.
        /// </summary>
        public static string SubMenuFamiliaAplicarFactor {
            get {
                return ResourceManager.GetString("SubMenuFamiliaAplicarFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency - Apply Factor.
        /// </summary>
        public static string SubMenuMonedaAplicarFactor {
            get {
                return ResourceManager.GetString("SubMenuMonedaAplicarFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string SubMenuSalir {
            get {
                return ResourceManager.GetString("SubMenuSalir", resourceCulture);
            }
        }
    }
}
